// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolaHub.Infrastructure.Persistence;

#nullable disable

namespace SolaHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502193000_HardenAuthAndIntegrity")]
    partial class HardenAuthAndIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolaHub.Core.Entities.Church", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_churches");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("ix_churches_admin_id");

                    b.ToTable("churches", (string)null);
                });

            modelBuilder.Entity("SolaHub.Core.Entities.ReadingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reading_plans");

                    b.HasIndex("ChurchId")
                        .HasDatabaseName("ix_reading_plans_church_id")
                        .HasFilter("church_id IS NOT NULL");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_reading_plans_created_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_reading_plans_status");

                    b.ToTable("reading_plans", (string)null);
                });

            modelBuilder.Entity("SolaHub.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChurchId")
                        .HasColumnType("uuid")
                        .HasColumnName("church_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<int>("SessionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("session_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ChurchId")
                        .HasDatabaseName("ix_users_church_id")
                        .HasFilter("church_id IS NOT NULL");

                    b.HasIndex("RefreshToken")
                        .HasDatabaseName("ix_users_refresh_token")
                        .HasFilter("refresh_token IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SolaHub.Core.Entities.VerseNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.PrimitiveCollection<string>("_tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_verse_notes");

                    b.HasIndex("IsShared")
                        .HasDatabaseName("ix_verse_notes_is_shared")
                        .HasFilter("is_shared = true");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_verse_notes_user_id");

                    b.ToTable("verse_notes", (string)null);
                });

            modelBuilder.Entity("SolaHub.Core.Entities.ReadingPlan", b =>
                {
                    b.OwnsMany("SolaHub.Core.Entities.PlanParticipant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("plan_id")
                                .HasColumnType("uuid")
                                .HasColumnName("plan_id");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<int>("CurrentDay")
                                .HasColumnType("integer")
                                .HasColumnName("current_day");

                            b1.Property<DateTimeOffset>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.HasKey("plan_id", "UserId")
                                .HasName("pk_plan_participants");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("ix_plan_participants_user_id");

                            b1.ToTable("plan_participants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("plan_id")
                                .HasConstraintName("fk_plan_participants_reading_plans_plan_id");

                            b1.HasOne("SolaHub.Core.Entities.User", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_plan_participants_users_user_id");
                        });

                    b.OwnsMany("SolaHub.Core.Entities.ReadingPlanDay", "Days", b1 =>
                        {
                            b1.Property<Guid>("plan_id")
                                .HasColumnType("uuid")
                                .HasColumnName("plan_id");

                            b1.Property<int>("DayNumber")
                                .HasColumnType("integer")
                                .HasColumnName("day_number");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("title");

                            b1.PrimitiveCollection<string>("_verseRefKeys")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("verse_refs");

                            b1.HasKey("plan_id", "DayNumber")
                                .HasName("pk_reading_plan_days");

                            b1.ToTable("reading_plan_days", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("plan_id")
                                .HasConstraintName("fk_reading_plan_days_reading_plans_plan_id");
                        });

                    b.Navigation("Days");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("SolaHub.Core.Entities.Church", b =>
                {
                    b.HasOne("SolaHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_churches_users_admin_id");
                });

            modelBuilder.Entity("SolaHub.Core.Entities.ReadingPlan", b =>
                {
                    b.HasOne("SolaHub.Core.Entities.Church", null)
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reading_plans_churches_church_id");

                    b.HasOne("SolaHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reading_plans_users_created_by");
                });

            modelBuilder.Entity("SolaHub.Core.Entities.User", b =>
                {
                    b.HasOne("SolaHub.Core.Entities.Church", null)
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_churches_church_id");

                    b.OwnsOne("SolaHub.Core.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_users_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("SolaHub.Core.Entities.VerseNote", b =>
                {
                    b.HasOne("SolaHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verse_notes_users_user_id");

                    b.OwnsOne("SolaHub.Core.ValueObjects.VerseRef", "VerseRef", b1 =>
                        {
                            b1.Property<Guid>("VerseNoteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("BookShort")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("verse_book");

                            b1.Property<int>("Chapter")
                                .HasColumnType("integer")
                                .HasColumnName("verse_chapter");

                            b1.Property<int>("Verse")
                                .HasColumnType("integer")
                                .HasColumnName("verse_number");

                            b1.HasKey("VerseNoteId");

                            b1.ToTable("verse_notes");

                            b1.WithOwner()
                                .HasForeignKey("VerseNoteId")
                                .HasConstraintName("fk_verse_notes_verse_notes_id");
                        });

                    b.Navigation("VerseRef")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
